import type { Metadata } from 'next'
import { Noto_Serif_JP } from 'next/font/google'
import { Playfair_Display } from 'next/font/google'

import './globals.css'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

const notoSerif = Noto_Serif_JP({ variable: '--font-noto-serif', subsets: ['latin'] })
const playfair = Playfair_Display({ variable: '--font-playfair', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSerif.variable} ${playfair.variable} antialiased`}>
        <div className="absolute top-0 left-0 w-full z-20">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
